import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { GAME_REGISTRY } from "./registry";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const OUTPUT = join(
  ROOT,
  "apps-native/games/packages/platform_core/lib/src/generated/game_app_registry.dart",
);

function quote(value: string): string {
  return `'${value.replaceAll("'", "\\'")}'`;
}

export function generateRegistry(): void {
  const entries = GAME_REGISTRY.map(
    (game) => `    GameAppDefinition(
      id: ${quote(game.id)},
      canonicalName: ${quote(game.canonicalName)},
      publicTitle: ${quote(game.publicTitle)},
      saveNamespacePrefix: ${quote(game.namespaces.save)},
      saveSchemaVersion: ${game.namespaces.saveSchemaVersion},
      analyticsNamespacePrefix: ${quote(game.namespaces.analytics)},
      iosBundleId: ${quote(game.identity.iosBundleId)},
      androidApplicationId: ${quote(game.identity.androidApplicationId)},
      debugSuffix: ${quote(game.identity.debugSuffix)},
      environments: const [${game.environments.map(quote).join(", ")}],
      rendering: ${quote(game.rendering)},
    ),`,
  ).join("\n");
  const output = `// Generated by scripts/games/codegen.ts — DO NOT EDIT

class GameAppDefinition {
  const GameAppDefinition({
    required this.id,
    required this.canonicalName,
    required this.publicTitle,
    required this.saveNamespacePrefix,
    required this.saveSchemaVersion,
    required this.analyticsNamespacePrefix,
    required this.iosBundleId,
    required this.androidApplicationId,
    required this.debugSuffix,
    required this.environments,
    required this.rendering,
  });

  final String id;
  final String canonicalName;
  final String publicTitle;
  final String saveNamespacePrefix;
  final int saveSchemaVersion;
  final String analyticsNamespacePrefix;
  final String iosBundleId;
  final String androidApplicationId;
  final String debugSuffix;
  final List<String> environments;
  final String rendering;

  String saveNamespaceFor(String environment) => '$saveNamespacePrefix.$environment';

  String analyticsNamespaceFor(String environment) => '$analyticsNamespacePrefix.$environment';
}

abstract final class GeneratedGameRegistry {
  static const apps = <GameAppDefinition>[
${entries}
  ];

  static GameAppDefinition? byId(String id) {
    for (final app in apps) {
      if (app.id == id) return app;
    }
    return null;
  }
}
`;
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, output);
  execFileSync("dart", ["format", OUTPUT], { cwd: ROOT, stdio: "ignore" });
  console.log(`Generated ${GAME_REGISTRY.length} game registry entries at ${OUTPUT}`);
}

if (import.meta.main) generateRegistry();
