import {
  capabilities,
  type GameRegistration,
  identity,
  internalSource,
  namespaces,
  noPermissions,
  scaffoldReadiness,
  source,
  supportedEnvironments,
} from "./registry-types";

export const GAME_REGISTRY: readonly GameRegistration[] = [
  {
    id: "merge_relay",
    canonicalName: "Merge Relay",
    publicTitle: "Merge Relay",
    subtitle: "Merge tiles. Challenge friends",
    lifecycle: "concept",
    paths: {
      app: "apps-native/games/merge_relay",
      rulesPackage: "apps-native/games/packages/merge_rules",
    },
    source: source(
      "1bFFgFE6bEDIbGVTSxDGT8nbMZoBxyRkv",
      "1MJMWtgjZSFfjHB7y6rmjsF65jl01Wmsk",
      "1A8ib92CGqfUHqc7-kmoUT3kzwpjdmOrK",
      "1EzTnN_gSBWJO5DIF-bmKPNK8cGbrPBny",
      null,
    ),
    platforms: ["ios", "android"],
    environments: supportedEnvironments,
    rendering: "flame",
    capabilities: capabilities([
      "game_loop",
      "guest_identity",
      "save_sync",
      "billing",
      "ads",
      "sharing",
    ]),
    permissions: noPermissions,
    readiness: scaffoldReadiness,
    identity: identity("mergerelay"),
    namespaces: namespaces("merge_relay"),
    release: {
      version: "0.1.0",
      buildNumber: 1,
      storeProductIds: { ios: null, android: null },
      publisher: null,
      domains: [],
    },
  },
  {
    id: "pocket_biome",
    canonicalName: "Pocket Biome",
    publicTitle: "Pocket Biome",
    subtitle: "Grow a tiny living world",
    lifecycle: "concept",
    paths: {
      app: "apps-native/games/pocket_biome",
      rulesPackage: "apps-native/games/packages/biome_rules",
    },
    source: source(
      "1vSp7KrVxMNdTPqP_3hzRQ7kr9HB7kJeZ",
      "1BuNUE6IlMVKs37nJ30mpdEGH3_iFs1PP",
      "1JMY2Yt-w0q54LchlJ8BNn2rpPLwCpxSb",
      "1_QZMfUWRio5EP_LBy6ofwmq5A76kN1xu",
      null,
    ),
    platforms: ["ios", "android"],
    environments: supportedEnvironments,
    rendering: "flame",
    capabilities: capabilities(["game_loop", "save_sync", "billing", "sharing", "notifications"]),
    permissions: noPermissions,
    readiness: scaffoldReadiness,
    identity: identity("pocketbiome"),
    namespaces: namespaces("pocket_biome"),
    release: {
      version: "0.1.0",
      buildNumber: 1,
      storeProductIds: { ios: null, android: null },
      publisher: null,
      domains: [],
    },
  },
  {
    id: "sixty_second_heist",
    canonicalName: "Sixty-Second Heist",
    publicTitle: "Sixty-Second Heist",
    subtitle: "Plan. Sneak. Escape.",
    lifecycle: "concept",
    paths: {
      app: "apps-native/games/sixty_second_heist",
      rulesPackage: "apps-native/games/packages/heist_rules",
    },
    source: source(
      "1BENH1-3-tmnQlh3m16zlk0_Ut63PkBZo",
      "1-_MqNs9Ul080QmH05rHsLORSGRq83F9J",
      "1rYuGJ2CMTOY8oFfrWIOIaPsHd5B3QA31",
      "1hbkoiUUOfXLWGuzJjyEfOeZY8hqif1M2",
      null,
    ),
    platforms: ["ios", "android"],
    environments: supportedEnvironments,
    rendering: "flame",
    capabilities: capabilities(["game_loop", "save_sync", "billing", "ads", "sharing"]),
    permissions: noPermissions,
    readiness: scaffoldReadiness,
    identity: identity("sixtysecondheist"),
    namespaces: namespaces("sixty_second_heist"),
    release: {
      version: "0.1.0",
      buildNumber: 1,
      storeProductIds: { ios: null, android: null },
      publisher: null,
      domains: [],
    },
  },
  {
    id: "meme_court",
    canonicalName: "Meme Court",
    publicTitle: "Meme Court",
    subtitle: "Caption battles with friends",
    lifecycle: "concept",
    paths: {
      app: "apps-native/games/meme_court",
      rulesPackage: "apps-native/games/packages/court_rules",
    },
    source: source(
      "1X6UE5pvTtDxNhUYNHGRVp1A5XKlCeGad",
      "14xC0VFZywMMT3hETrKQoAtf7ZwnfwBI3",
      "1073cIXJsPuQvwDCN2gCp6dkMzE-CaxsL",
      "1dm1TlyzALuZcSgitHvBvK1SLkh6fsT0N",
      null,
    ),
    platforms: ["ios", "android"],
    environments: supportedEnvironments,
    rendering: "flutter_widgets",
    capabilities: capabilities(["save_sync", "billing", "sharing", "moderation", "web_voting"]),
    permissions: noPermissions,
    readiness: scaffoldReadiness,
    identity: identity("memecourt"),
    namespaces: namespaces("meme_court"),
    release: {
      version: "0.1.0",
      buildNumber: 1,
      storeProductIds: { ios: null, android: null },
      publisher: null,
      domains: [],
    },
  },
  {
    id: "snapquest",
    canonicalName: "SnapQuest",
    publicTitle: "Peeklings",
    subtitle: "Find objects. Meet creatures",
    lifecycle: "concept",
    paths: {
      app: "apps-native/games/snapquest",
      rulesPackage: "apps-native/games/packages/snapquest_rules",
    },
    source: source(
      "1uB2q8utiOSwCENVhX3yFHbwm6pmjDhnc",
      "15qaZXs1Z1CF2XXTRPtqgTqcat8m9nb",
      "1ACvWairYy-8v8vqq1cId_oJKuWpYhG1Q",
      "1GD_bS-niOlam1AYn2z5draah5JJOX5ep",
      "Apps/SnapQuest/",
    ),
    platforms: ["ios", "android"],
    environments: supportedEnvironments,
    rendering: "flame",
    capabilities: {
      specified: ["game_loop", "camera", "save_sync", "billing", "sharing", "notifications"],
      implemented: ["camera"],
      enabled: ["camera"],
    },
    permissions: { specified: ["camera"], enabled: ["camera"] },
    readiness: scaffoldReadiness,
    identity: identity("snapquest"),
    namespaces: namespaces("snapquest"),
    release: {
      version: "0.1.0",
      buildNumber: 1,
      storeProductIds: { ios: null, android: null },
      publisher: null,
      domains: [],
    },
  },
  {
    id: "ludo",
    canonicalName: "Ludo",
    publicTitle: "Ludo",
    subtitle: "Roll, race, and capture with friends",
    lifecycle: "concept",
    paths: {
      app: "apps-native/games/ludo",
      rulesPackage: "apps-native/games/packages/ludo_rules",
    },
    source: internalSource(
      "docs-internal/gaming",
      "ludo-implementation-plan",
      "ludo-mobile-ui-plan",
      "ludo-flutter-plan",
      {
        index: "docs-internal/gaming/ludo-implementation-plan.md",
        prd: "docs-internal/gaming/ludo-mobile-ui-plan.md",
        validation: "docs-internal/gaming/ludo-flutter-plan.md",
      },
    ),
    platforms: ["android"],
    environments: supportedEnvironments,
    rendering: "flame",
    capabilities: capabilities(["game_loop", "guest_identity", "save_sync", "sharing"]),
    permissions: noPermissions,
    readiness: scaffoldReadiness,
    identity: identity("ludo"),
    namespaces: namespaces("ludo"),
    release: {
      version: "0.1.0",
      buildNumber: 1,
      storeProductIds: { ios: null, android: null },
      publisher: null,
      domains: [],
    },
  },
] as const;
