name: ludo
description: Ludo Flutter client.
publish_to: none
resolution: workspace
version: 0.1.0+1

environment:
  sdk: ">=3.13.3 <4.0.0"
  flutter: ">=3.47.3"

dependencies:
  audioplayers: ^6.8.1
  flame: 1.38.2
  flutter:
    sdk: flutter
  ludo_rules:
    path: ../packages/ludo_rules
  path_provider: ^2.1.5
  platform_core:
    path: ../packages/platform_core

dev_dependencies:
  flame_test: ^2.3.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - content/
  fonts:
    - family: LilitaOne
      fonts:
        - asset: assets/fonts/LilitaOne/LilitaOne-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
