import 'dart:convert';
import 'dart:io';

import 'package:merge_rules/merge_rules.dart';
import 'package:test/test.dart';

/// Task 13 (round 2): both the Dart engine (this package) and the
/// TypeScript server engine (`packages/api/src/games/merge-relay/engine.ts`,
/// see its `engine.test.ts`) load the SAME checked-in JSON fixture and
/// assert the same expectations from it — the one cross-runtime check that
/// would have caught the right/down double-reversal bug directly, since it
/// exercises a move sequence that includes both `right` and `down`.
///
/// Regenerated by hand from this package's own `MergeRules` after the
/// right/down fix (see `.agents/resources/2026-09-25/games-wave2-qa/13/README.md`
/// for the before/after values and how each was derived).
void main() {
  late Map<String, Object?> fixture;

  setUpAll(() {
    fixture =
        jsonDecode(
              _findRepoFile(
                'scripts/games/merge_relay_domain_fixture.json',
              ).readAsStringSync(),
            )
            as Map<String, Object?>;
  });

  test('checkpoint hash matches the checked-in fixture', () {
    final checkpoint = MergeCheckpoint.fromJson(
      (fixture['checkpoint']! as Map).cast<String, Object?>(),
    );
    expect(checkpoint.checkpointHash, fixture['checkpoint_hash']);
  });

  test(
    'ordinary replay matches the checked-in fixture (includes right and down)',
    () {
      const rules = MergeRules();
      final checkpoint = MergeCheckpoint.fromJson(
        (fixture['checkpoint']! as Map).cast<String, Object?>(),
      );
      final ordinary = (fixture['ordinary_replay']! as Map)
          .cast<String, Object?>();
      final moves = (ordinary['moves']! as List)
          .cast<String>()
          .map(_parseDirection)
          .toList();
      final result = rules.replay(checkpoint.state.seed, moves);
      expect(result.toJson(), ordinary['expected']);
    },
  );

  test(
    'ranked replay (max_legal_moves budget) matches the checked-in fixture',
    () {
      const rules = MergeRules();
      final checkpoint = MergeCheckpoint.fromJson(
        (fixture['checkpoint']! as Map).cast<String, Object?>(),
      );
      final ranked = (fixture['ranked_replay']! as Map).cast<String, Object?>();
      final moves = (ranked['moves']! as List)
          .cast<String>()
          .map(_parseDirection)
          .toList();
      final maxLegalMoves = ranked['max_legal_moves']! as int;
      final result = rules.replayFrom(
        checkpoint.state,
        moves,
        rejectNoOp: true,
        maxLegalMoves: maxLegalMoves,
      );
      expect(result.finalState.toJson(), ranked['expected']);
      expect(result.scoreGained, ranked['score_gained']);
      expect(result.maxTile, ranked['max_tile']);
      expect(mergeAttemptOutcomeName(result.outcome), ranked['outcome']);
    },
  );
}

MergeDirection _parseDirection(String value) => switch (value) {
  'up' => MergeDirection.up,
  'down' => MergeDirection.down,
  'left' => MergeDirection.left,
  'right' => MergeDirection.right,
  _ => throw FormatException('unknown move: $value'),
};

/// Walks upward from the process's working directory looking for
/// `relativePath`, so this test works whether `dart test` is invoked from
/// this package's own directory (the normal case — see
/// `scripts/games/cli-commands.ts`) or from the repo root.
File _findRepoFile(String relativePath) {
  var directory = Directory.current;
  for (var depth = 0; depth < 8; depth += 1) {
    final candidate = File('${directory.path}/$relativePath');
    if (candidate.existsSync()) return candidate;
    final parent = directory.parent;
    if (parent.path == directory.path) break;
    directory = parent;
  }
  throw FileSystemException(
    'Could not locate $relativePath above ${Directory.current.path}',
  );
}
