import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = join(ROOT, "apps-native/ios-app/Starter/Generated");
const HEADER = "// Generated by scripts/codegen-swift.ts — DO NOT EDIT\n";

function generateAppConfigKeys(): void {
  const configKeys = [
    "version_config",
    "feature_flags",
    "maintenance_mode",
    "store_urls",
    "support_urls",
  ];
  const cases = configKeys
    .map((k) => `    case ${k.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())} = "${k}"`)
    .join("\n");
  const swift = `${HEADER}
enum AppConfigKey: String {
${cases}
}
`;
  writeFileSync(join(GENERATED, "AppConfigKeys.swift"), swift);
}

function generateAnalyticsEvents(): void {
  const eventTypes = [
    "screen_view",
    "auth_sign_in",
    "auth_sign_out",
    "chat_message_sent",
    "subscription_started",
  ];
  const cases = eventTypes
    .map((t) => `    case ${t.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())} = "${t}"`)
    .join("\n");
  const swift = `${HEADER}
enum AnalyticsEventType: String {
${cases}
}
`;
  writeFileSync(join(GENERATED, "AnalyticsEvents.swift"), swift);
}

function generateDesignTokens(): void {
  const light = {
    background: "#FFFFFF",
    surface: "#F2F2F7",
    text: "#000000",
    textSecondary: "#6C6C70",
    border: "#C6C6C8",
    primary: "#007AFF",
  };
  const dark = {
    background: "#000000",
    surface: "#1C1C1E",
    text: "#FFFFFF",
    textSecondary: "#8E8E93",
    border: "#38383A",
    primary: "#0A84FF",
  };

  function toSwiftColor(hex: string): string {
    const r = Number.parseInt(hex.slice(1, 3), 16) / 255;
    const g = Number.parseInt(hex.slice(3, 5), 16) / 255;
    const b = Number.parseInt(hex.slice(5, 7), 16) / 255;
    return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
  }

  const lightProps = Object.entries(light)
    .map(([k, v]) => `        static let ${k} = ${toSwiftColor(v)}`)
    .join("\n");
  const darkProps = Object.entries(dark)
    .map(([k, v]) => `        static let ${k} = ${toSwiftColor(v)}`)
    .join("\n");

  const swift = `${HEADER}import SwiftUI

struct DesignTokens {
    struct Light {
${lightProps}
    }
    struct Dark {
${darkProps}
    }
}
`;
  writeFileSync(join(GENERATED, "DesignTokens.swift"), swift);
}

generateAppConfigKeys();
generateAnalyticsEvents();
generateDesignTokens();
console.log("Generated 3 files into apps-native/ios-app/Starter/Generated/");
