import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { analyticsEventTypes, configKeys, designTokens } from "./codegen/registry";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = join(ROOT, "apps-native/ios-app/Starter/Generated");
const HEADER = "// Generated by scripts/codegen-swift.ts — DO NOT EDIT\n";

function generateAppConfigKeys(): void {
  const cases = configKeys
    .map((k) => `    case ${k.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())} = "${k}"`)
    .join("\n");
  const swift = `${HEADER}
enum AppConfigKey: String {
${cases}
}
`;
  writeFileSync(join(GENERATED, "AppConfigKeys.swift"), swift);
}

function generateAnalyticsEvents(): void {
  const cases = analyticsEventTypes
    .map((t) => `    case ${t.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())} = "${t}"`)
    .join("\n");
  const swift = `${HEADER}
enum AnalyticsEventType: String {
${cases}
}
`;
  writeFileSync(join(GENERATED, "AnalyticsEvents.swift"), swift);
}

function generateDesignTokens(): void {
  const { light, dark } = designTokens;

  function toSwiftColor(hex: string): string {
    const r = Number.parseInt(hex.slice(1, 3), 16) / 255;
    const g = Number.parseInt(hex.slice(3, 5), 16) / 255;
    const b = Number.parseInt(hex.slice(5, 7), 16) / 255;
    return `Color(red: ${r.toFixed(4)}, green: ${g.toFixed(4)}, blue: ${b.toFixed(4)})`;
  }

  const lightProps = Object.entries(light)
    .map(([k, v]) => `        static let ${k} = ${toSwiftColor(v)}`)
    .join("\n");
  const darkProps = Object.entries(dark)
    .map(([k, v]) => `        static let ${k} = ${toSwiftColor(v)}`)
    .join("\n");

  const swift = `${HEADER}import SwiftUI

struct DesignTokens {
    struct Light {
${lightProps}
    }
    struct Dark {
${darkProps}
    }
}
`;
  writeFileSync(join(GENERATED, "DesignTokens.swift"), swift);
}

generateAppConfigKeys();
generateAnalyticsEvents();
generateDesignTokens();
console.log("Generated 3 files into apps-native/ios-app/Starter/Generated/");
