import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { analyticsEventTypes, configKeys, designTokens } from "./codegen/registry";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = join(ROOT, "apps-native/flutter-app/lib/generated");
const HEADER = "// Generated by scripts/codegen-dart.ts — DO NOT EDIT\n";

function toCamelCase(snake: string): string {
  return snake.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

function generateAppConfigKeys(): void {
  const entries = configKeys.map((k) => `  ${toCamelCase(k)}('${k}')`).join(",\n");
  const dart = `${HEADER}
enum AppConfigKey {
${entries};

  const AppConfigKey(this.value);

  final String value;
}
`;
  writeFileSync(join(GENERATED, "app_config_keys.dart"), dart);
}

function generateAnalyticsEvents(): void {
  const entries = analyticsEventTypes.map((t) => `  ${toCamelCase(t)}('${t}')`).join(",\n");
  const dart = `${HEADER}
enum AnalyticsEventType {
${entries};

  const AnalyticsEventType(this.value);

  final String value;
}
`;
  writeFileSync(join(GENERATED, "analytics_events.dart"), dart);
}

function generateDesignTokens(): void {
  const { light, dark } = designTokens;

  function toDartColor(hex: string): string {
    const rgb = hex.slice(1).toUpperCase();
    return `Color(0xFF${rgb})`;
  }

  const lightProps = Object.entries(light)
    .map(([k, v]) => `  final Color ${k} = ${toDartColor(v)};`)
    .join("\n");
  const darkProps = Object.entries(dark)
    .map(([k, v]) => `  final Color ${k} = ${toDartColor(v)};`)
    .join("\n");

  const dart = `${HEADER}import 'package:flutter/material.dart';

class DesignTokens {
  DesignTokens._();

  static const DesignTokensLight light = DesignTokensLight();
  static const DesignTokensDark dark = DesignTokensDark();
}

class DesignTokensLight {
  const DesignTokensLight();

${lightProps}
}

class DesignTokensDark {
  const DesignTokensDark();

${darkProps}
}
`;
  writeFileSync(join(GENERATED, "design_tokens.dart"), dart);
}

mkdirSync(GENERATED, { recursive: true });
generateAppConfigKeys();
generateAnalyticsEvents();
generateDesignTokens();
console.log("Generated 3 files into apps-native/flutter-app/lib/generated/");
